version: '2.0'
services:
    tkw_skeleton_simulator:
        ports:
            - '4848:4848'
        volumes:
            # invert comments status for all_evidence config
            #- '${TKWROOT}/config/SKELETON:/home/service/data'
            - '${TKWROOT}/config/SKELETON/simulator_saved_messages:/home/service/TKW/config/SKELETON/simulator_saved_messages'
            - '${TKWROOT}/config/SKELETON/validator_reports:/home/service/TKW/config/SKELETON/validator_reports'
            - '${TKWROOT}/config/SKELETON/logs:/home/service/TKW/config/SKELETON/logs'
        image: 'nhsdigitalmait/tkw_skeleton_simulator:0.1'
