FROM nhsdigitalmait/tkw-x:a558e32
ARG USER_ID

RUN useradd -rm -u $USER_ID service
RUN mkdir /home/service/data/ && chown service:service /home/service/data/
VOLUME /home/service/data
VOLUME /home/service/certs
COPY . /home/service/TKW/config/SKELETON
WORKDIR /home/service/TKW/config/SKELETON
RUN mkdir /home/service/TKW/config/SKELETON/simulator_saved_messages/  && chown service:service /home/service/TKW/config/SKELETON/simulator_saved_messages
RUN mkdir /home/service/TKW/config/SKELETON/messages_for_validation/  && chown service:service /home/service/TKW/config/SKELETON/messages_for_validation
RUN mkdir /home/service/TKW/config/SKELETON/transmitter_sent_messages/  && chown service:service /home/service/TKW/config/SKELETON/transmitter_sent_messages

RUN sh set-all-configurations.sh

ENV trustStore=default
ENV trustStorePassword=default
ENV keyStore=default
ENV keyStorePassword=default
USER service
ENTRYPOINT ["bash", "runtkwfhirvalidator.sh"]

